### PR TITLE
new samples added

### PR DESCRIPTION
**Pull request by Koustavjr**
@mailtodanish  can u please check my pr

### CODE REVIEW

**Comment by Koustavjr** [comment]
@mailtodanish can u please check my pr.

**Comment by mailtodanish** [comment]
please update readme.md

**Comment by Koustavjr** [comment]
@mailtodanish i have updated the readme can u please check my pr.

**Comment by Koustavjr** [comment]
@mailtodanish is it alright?

**Review by mailtodanish — APPROVED** [review]

**Pull request merged**
